ORG_ID = 'atlas.org.id'
ORG_NAME = 'atlas.org.name'
ORG_API_KEY = 'atlas.org.api.key'
ORG_API_KEY_VALID = 'atlas.org.api.key.valid'
ORG_SITE = 'atlas.org.site'
USER_MAIL = 'atlas.user.mail'
USER_PAT = 'atlas.user.pat'
USER_PAT_VALID = 'atlas.user.pat.valid'
PW_OBF = '*************************'
JWM_KEY = 'com.atlassian.jira.jira-work-management'
JSM_KEY = 'com.atlassian.servicedesk'
JIRA_TOOLKIT_KEY = 'com.atlassian.jira.toolkit'
JSW_KEY = 'com.atlassian.jira.jira-software'
JSW_NAME = 'Jira Software'
CONF_KEY = 'com.atlassian.confluence'
CONF_NAME = 'Confluence'

